/**
 * UX-11: stable public AppErrorPayload / DownloadError codes that must have
 * localized user-facing copy. Raw backend messages stay in diagnostics only.
 */
export const STABLE_ERROR_CODES = [
  "auth_headers_expired",
  "auth_headers_unavailable",
  "body_error",
  "bt_file_selection_required",
  "bt_metadata_failed",
  "bt_metadata_timeout",
  "bt_runtime_stats_failed",
  "bt_source_failed",
  "canceled",
  "connection_refused",
  "dash_empty_output",
  "dash_ffmpeg_failed",
  "dash_ffmpeg_missing",
  "dash_invalid_manifest",
  "dash_live_unsupported",
  "dash_mpd_too_large",
  "dash_multi_period_unsupported",
  "dash_no_duration",
  "dash_no_segments",
  "dash_no_tracks",
  "dash_segment_failed",
  "dash_segment_stalled",
  "dash_segment_timeline_unsupported",
  "dash_template_unsupported",
  "decode_error",
  "disk_write_failed",
  "dns_failure",
  "download_failed",
  "duplicate_task",
  "ffmpeg_missing",
  "ffmpeg_not_found",
  "final_path_conflict",
  "ftp_auth_failed",
  "ftp_connect_failed",
  "ftp_proxy_unsupported_for_implicit_tls",
  "ftp_read_failed",
  "ftp_read_timeout",
  "ftp_tls_handshake_failed",
  "hls_ffmpeg_missing",
  "hls_init_too_large",
  "hls_invalid_playlist",
  "hls_live_idle",
  "hls_segment_failed",
  "hls_segment_stalled",
  "hls_segment_too_large",
  "hls_track_failed",
  "hls_unsupported_encryption",
  "http_denied",
  "http_not_found",
  "io_error",
  "metalink_all_mirrors_failed",
  "metalink_invalid_manifest",
  "metalink_manifest_too_large",
  "metalink_mirror_unsupported_range",
  "metalink_no_files",
  "metalink_no_healthy_mirrors",
  "metalink_no_resources",
  "metalink_partial_completion",
  "network_error",
  "network_unreachable",
  "proxy_auth_failed",
  "proxy_configuration_invalid",
  "proxy_connect_failed",
  "proxy_connection_failed",
  "proxy_scheme_unsupported_for_task",
  "proxy_secret_decrypt_failed",
  "proxy_secret_encrypt_failed",
  "proxy_timeout",
  "redirect_error",
  "remote_changed",
  "resume_mismatch",
  "resume_unavailable",
  "server_rate_limited",
  "sftp_auth_failed",
  "sftp_channel_failed",
  "sftp_connect_failed",
  "sftp_credentials_required",
  "sftp_directory_not_file",
  "sftp_directory_probe_failed",
  "sftp_host_key_changed",
  "sftp_invalid_url",
  "sftp_open_failed",
  "sftp_probe_state_unavailable",
  "sftp_proxy_unsupported",
  "sftp_read_failed",
  "sftp_read_timeout",
  "sftp_resume_failed",
  "sftp_short_read",
  "sftp_size_mismatch",
  "sftp_stat_failed",
  "sftp_subsystem_failed",
  "task_credentials_decrypt_failed",
  "task_credentials_encrypt_failed",
  "task_credentials_invalid",
  "task_credentials_unavailable",
  "temp_file_missing",
  "temp_file_smaller_than_progress",
  "timeout",
  "tls_error",
  "unknown_error",
  "webdav_invalid_multistatus",
  "webdav_propfind_failed",
  "webdav_propfind_too_large",
] as const;

export type StableErrorCode = (typeof STABLE_ERROR_CODES)[number];

function toI18nKey(code: string): string {
  return `errors.${code.replace(/_([a-z])/g, (_, ch: string) => ch.toUpperCase())}`;
}

/** Map every stable code to its i18n key (camelCase under errors.*). */
export const ERROR_CODE_I18N_MAP: Record<string, string> = Object.fromEntries(
  STABLE_ERROR_CODES.map((code) => [code, toI18nKey(code)]),
);

/** English user-facing copy for stable error codes. */
export const STABLE_ERROR_MESSAGES_EN: Record<StableErrorCode, string> = {
  auth_headers_expired: "Authentication credentials have expired. Check the URL and retry.",
  auth_headers_unavailable: "Authentication credentials are unavailable. Provide credentials and retry.",
  body_error: "The response body could not be read. Retry the download.",
  bt_file_selection_required: "Select at least one file before starting this torrent.",
  bt_metadata_failed: "BitTorrent metadata could not be retrieved.",
  bt_metadata_timeout: "Timed out waiting for BitTorrent metadata.",
  bt_runtime_stats_failed: "BitTorrent runtime statistics are unavailable.",
  bt_source_failed: "The torrent or magnet source could not be loaded.",
  canceled: "The download was canceled.",
  connection_refused: "The connection was refused by the remote host.",
  dash_empty_output: "DASH download produced an empty output file.",
  dash_ffmpeg_failed: "ffmpeg failed while processing the DASH stream.",
  dash_ffmpeg_missing: "ffmpeg is required for DASH downloads. Configure it in Settings.",
  dash_invalid_manifest: "The DASH manifest is invalid or unsupported.",
  dash_live_unsupported: "Live DASH streams are not supported yet.",
  dash_mpd_too_large: "The DASH manifest is too large to process safely.",
  dash_multi_period_unsupported: "Multi-Period DASH manifests are not supported yet.",
  dash_no_duration: "The DASH manifest does not declare a duration.",
  dash_no_segments: "No downloadable segments were found in the DASH manifest.",
  dash_no_tracks: "No audio or video tracks were found in the DASH manifest.",
  dash_segment_failed: "A DASH segment download failed.",
  dash_segment_stalled: "A DASH segment download stalled.",
  dash_segment_timeline_unsupported: "This DASH SegmentTimeline layout is not supported yet.",
  dash_template_unsupported: "This DASH SegmentTemplate uses placeholders that are not supported yet.",
  decode_error: "The response could not be decoded.",
  disk_write_failed: "Writing to disk failed. Free up space or choose another folder.",
  dns_failure: "DNS lookup failed. Check the hostname and your network.",
  download_failed: "The download failed.",
  duplicate_task: "A download for this resource already exists.",
  ffmpeg_missing: "ffmpeg is required for this task. Configure it in Settings.",
  ffmpeg_not_found: "ffmpeg was not found. Configure the path in Settings.",
  final_path_conflict: "The destination file already exists. Choose another name or folder.",
  ftp_auth_failed: "FTP authentication failed. Check the username and password.",
  ftp_connect_failed: "Could not connect to the FTP server.",
  ftp_proxy_unsupported_for_implicit_tls: "The configured proxy does not support implicit FTPS.",
  ftp_read_failed: "Reading from the FTP server failed.",
  ftp_read_timeout: "The FTP read timed out.",
  ftp_tls_handshake_failed: "The FTP TLS handshake failed.",
  hls_ffmpeg_missing: "ffmpeg is required for HLS remuxing. Configure it in Settings.",
  hls_init_too_large: "The HLS initialization segment is too large.",
  hls_invalid_playlist: "The HLS playlist is invalid or unsupported.",
  hls_live_idle: "The live HLS playlist stopped publishing new segments. Resume to keep polling.",
  hls_segment_failed: "An HLS segment download failed.",
  hls_segment_stalled: "An HLS segment download stalled.",
  hls_segment_too_large: "An HLS segment exceeded the size limit.",
  hls_track_failed: "A selected HLS audio or subtitle track could not be downloaded.",
  hls_unsupported_encryption: "This HLS encryption method is not supported.",
  http_denied: "Access denied (403). Check the URL or credentials.",
  http_not_found: "The resource was not found (404). Check the URL.",
  io_error: "A local file I/O error occurred.",
  metalink_all_mirrors_failed: "All Metalink mirrors failed.",
  metalink_invalid_manifest: "The Metalink manifest is invalid.",
  metalink_manifest_too_large: "The Metalink manifest is too large to process safely.",
  metalink_mirror_unsupported_range: "A Metalink mirror does not support resume ranges.",
  metalink_no_files: "The Metalink manifest contains no files.",
  metalink_no_healthy_mirrors: "No healthy Metalink mirrors remain.",
  metalink_no_resources: "The Metalink file has no downloadable resources.",
  metalink_partial_completion: "The Metalink download finished only partially.",
  network_error: "A network error interrupted the transfer.",
  network_unreachable: "The remote network is unreachable.",
  proxy_auth_failed: "Proxy authentication failed. Check proxy credentials.",
  proxy_configuration_invalid: "The proxy configuration is invalid.",
  proxy_connect_failed: "Could not connect through the proxy.",
  proxy_connection_failed: "The proxy connection failed.",
  proxy_scheme_unsupported_for_task: "This proxy scheme is not supported for the task protocol.",
  proxy_secret_decrypt_failed: "Stored proxy credentials could not be decrypted.",
  proxy_secret_encrypt_failed: "Proxy credentials could not be encrypted for storage.",
  proxy_timeout: "The proxy connection timed out.",
  redirect_error: "Following redirects failed.",
  remote_changed: "The remote file changed since the last download. Restart from the beginning.",
  resume_mismatch: "Resume validation failed because the remote file no longer matches.",
  resume_unavailable: "The server no longer supports resuming. Restart from the beginning.",
  server_rate_limited: "The server is rate-limiting requests. Try again later.",
  sftp_auth_failed: "SFTP authentication failed. Check credentials or key.",
  sftp_channel_failed: "Opening the SFTP channel failed.",
  sftp_connect_failed: "Could not connect to the SFTP server.",
  sftp_credentials_required: "SFTP credentials are required.",
  sftp_directory_not_file: "The SFTP path is a directory, not a file.",
  sftp_directory_probe_failed: "Probing the SFTP directory failed.",
  sftp_host_key_changed: "The SFTP host key changed. Forget the old key only if you trust the new one.",
  sftp_invalid_url: "The SFTP URL is invalid.",
  sftp_open_failed: "Opening the remote SFTP file failed.",
  sftp_probe_state_unavailable: "SFTP probe state is unavailable.",
  sftp_proxy_unsupported: "The configured proxy is not supported for SFTP.",
  sftp_read_failed: "Reading from the SFTP server failed.",
  sftp_read_timeout: "The SFTP read timed out.",
  sftp_resume_failed: "Resuming the SFTP download failed.",
  sftp_short_read: "The SFTP server returned fewer bytes than expected.",
  sftp_size_mismatch: "The remote SFTP file size no longer matches.",
  sftp_stat_failed: "Statting the remote SFTP file failed.",
  sftp_subsystem_failed: "Starting the SFTP subsystem failed.",
  task_credentials_decrypt_failed: "Stored task credentials could not be decrypted.",
  task_credentials_encrypt_failed: "Task credentials could not be encrypted for storage.",
  task_credentials_invalid: "Task credentials are invalid.",
  task_credentials_unavailable: "Task credentials are unavailable.",
  temp_file_missing: "The temporary download file is missing. Restart the download.",
  temp_file_smaller_than_progress: "The temporary file is smaller than the recorded progress. Restart the download.",
  timeout: "The request timed out.",
  tls_error: "A TLS/SSL error occurred while connecting.",
  unknown_error: "An unexpected error occurred.",
  webdav_invalid_multistatus: "The WebDAV multistatus response is invalid.",
  webdav_propfind_failed: "WebDAV PROPFIND failed.",
  webdav_propfind_too_large: "The WebDAV PROPFIND response is too large to process safely.",
};
