-- Rollback for migration 003: HLS audio/subtitle track selection (F-6)
--
-- SQLite does not support DROP COLUMN before 3.35.0 and the application
-- bundles its own SQLite build, but rolling back in production would also
-- lose the track selection data. This file is kept as documentation for
-- manual recovery only — `sqlx::migrate!` does NOT auto-execute files in
-- `migrations/rollback/`.
--
-- To roll back manually, take the database offline and run:
--
--     ALTER TABLE hls_tasks DROP COLUMN selected_audio_track_uris;
--     ALTER TABLE hls_tasks DROP COLUMN selected_subtitle_track_uris;
--
-- Then update `_sqlx_migrations` to remove the row for `003_hls_track_selection`.
--
-- This file intentionally contains only comments; do not run it as-is.
SELECT 1;
